In [1]:
# Let's start with some simple linear regression with gradient decent

In [2]:
# Regression with mse

In [22]:
import numpy as np
np.random.seed(42)

In [10]:
x = np.random.randint(10, size=5)
y = np.random.randint(10, size=5)
print(x, y)
print(x - y)
print((x - y) ** 2)
print(np.sum((x - y) ** 2) ** 0.5)

[2 5 0 1 1] [0 7 6 3 3]
[ 2 -2 -6 -2 -2]
[ 4  4 36  4  4]
7.211102550927978


In [78]:
def mse(t, p):
    return (np.sum((p - t) ** 2) ** 0.5) / t.shape[0]

In [ ]:
np.random.seed()

In [44]:
mask = np.random.uniform(size=5)
d = np.random.rand(5, 2)
print(mask, d)
d[mask > 0.5]

[0.52640266 0.73158952 0.08162998 0.06035208 0.24710323] [[0.15954468 0.87178357]
 [0.21921399 0.97586526]
 [0.33689579 0.18211792]
 [0.78969851 0.65870778]
 [0.49819572 0.55536355]]


array([[0.15954468, 0.87178357],
       [0.21921399, 0.97586526]])

In [51]:
def split(data, target, rate):
    mask = np.random.uniform(size=data.shape[0])
    return data[mask >= rate], target[mask >= rate], data[mask < rate], target[mask < rate]

In [99]:
tmp = np.random.rand(10, 3)
print(tmp)
print(tmp[:,1])

[[0.26951186 0.19092659 0.69464096]
 [0.21871561 0.59530327 0.26463503]
 [0.66196894 0.81493973 0.77802524]
 [0.76085133 0.18772241 0.08838495]
 [0.69894883 0.36834721 0.43234623]
 [0.03114909 0.25957645 0.0336764 ]
 [0.87918577 0.24339668 0.55733717]
 [0.03897932 0.66684739 0.32302735]
 [0.89791919 0.88811819 0.32529062]
 [0.9009609  0.99615767 0.82541566]]
[0.19092659 0.59530327 0.81493973 0.18772241 0.36834721 0.25957645
 0.24339668 0.66684739 0.88811819 0.99615767]


In [230]:
data = np.random.rand(100, 3)
target = 10 * data[:,0] + 20 * data[:,1] + 30 * data[:,2] + np.random.normal(size=100)

In [231]:
print(data.shape)
print(target.shape)

(100, 3)
(100,)


In [16]:
import sklearn

In [17]:
from sklearn import linear_model

In [18]:
validate_model = linear_model.LinearRegression()

In [234]:
train_data, train_target, test_data, test_target = split(data, target, 0.8)

In [240]:
validate_model.fit(test_data, test_target)
sklearn.metrics.mean_squared_error(train_target, validate_model.predict(train_data))  

1.3723933228976921

In [158]:
validate_model.coef_

array([10., 20., 30.])

In [69]:
X = np.random.rand(10, 3)
y = np.random.rand(10)
w = np.random.rand(X.shape[1])
pred = np.matmul(X, w)
print(mse(pred, y))
a = 2 * np.matmul(pred - y, X)
a.shape

0.156993514335475


(3,)

In [238]:
class LinearModel:
    def fit(self, X, y):
        self.weights = np.random.rand(X.shape[1])
        for i in range(100):
            y_pred = np.dot(X, self.weights)
            loss = mse(y, y_pred)
            print(np.sum((y - y_pred)**2) / len(y), self.weights)
            
            self.weights -= 0.01 * np.dot(y_pred - y, X)

In [239]:
m = LinearModel()
m.fit(test_data, test_target)

3.329638840773612 [0.31259802 0.41068263 0.20969028]
1.114842269271452 [12.87787384 13.9697818  14.74017403]
0.49338132431044257 [16.47912127 18.16982734 19.76164911]
0.3587962977637236 [17.27330587 19.42319646 21.74719023]
0.32310014026939277 [17.20350535 19.75437196 22.74380049]
0.3014228222216549 [16.88193018 19.80197604 23.40029957]
0.2827260792695169 [16.50053338 19.76697193 23.92371238]
0.265700007547186 [16.1186242  19.71215246 24.38136254]
0.25011027471886255 [15.75370571 19.65672945 24.7963021 ]
0.2358440397608116 [15.41016013 19.60620514 25.1774647 ]
0.2228072938227068 [15.08830336 19.56180249 25.52919976]
0.210913348400881 [14.78723956 19.52343948 25.85429335]
0.20008107838309278 [14.50575776 19.49066455 26.15493117]
0.19023425594166007 [14.24261033 19.46294841 26.43301065]
0.18130105772397215 [13.99659665 19.43977289 26.6902471 ]
0.1732136507950905 [13.76658551 19.42065585 26.92821407]
0.16590784888688856 [13.55151838 19.40515633 27.1483625 ]
0.1593228377016876 [13.35040698

In [148]:
train_target.shape

(22,)

In [235]:
10 * train_data[0][0] + 20 * train_data[0][1] + 30 * train_data[0][2]

28.179690617617403

In [236]:
train_target[0]

27.840999277695527

In [237]:
weights = np.zeros(3)
weights[0] = 9
weights[1] = 19
weights[2] = 29
for i in range(100):
    y_pred = np.dot(train_data, weights)
    grad = np.dot(y_pred - train_target, train_data)
    print(f"loss {np.sum(np.abs(y_pred - train_target)) / train_data.shape[0]} grad {grad} w {weights}")
    weights = weights - 0.01 * grad 
    

loss 1.6678862382107984 grad [-13.75364096 -14.45837359 -11.83550304] w [ 9. 19. 29.]
loss 1.5187870023690013 grad [-12.24812365 -12.73654007 -10.06499344] w [ 9.13753641 19.14458374 29.11835503]
loss 1.3883766508162978 grad [-10.92819558 -11.23117069  -8.52123805] w [ 9.26001765 19.27194914 29.21900496]
loss 1.2743029346104702 grad [-9.77054623 -9.91499593 -7.1756182 ] w [ 9.3692996  19.38426084 29.30421735]
loss 1.1745098834105951 grad [-8.7548004  -8.76418155 -6.00312118] w [ 9.46700506 19.4834108  29.37597353]
loss 1.097409906351235 grad [-7.86314847 -7.75789577 -4.98188597] w [ 9.55455307 19.57105262 29.43600474]
loss 1.0395811516670677 grad [-7.08002321 -6.87793109 -4.09280618] w [ 9.63318455 19.64863158 29.4858236 ]
loss 0.9888726858109876 grad [-6.39181737 -6.10837372 -3.31918309] w [ 9.70398478 19.71741089 29.52675166]
loss 0.9443896880000002 grad [-5.78663674 -5.43531459 -2.6464223 ] w [ 9.76790296 19.77849462 29.55994349]
loss 0.9142632373792295 grad [-5.2540844  -4.84659686

14.789077800802525 [0.04191522 0.41918288 0.16820366]
3.312481524615864 [78.18058309 73.57440531 92.93486733]
3.293121837745023 [77.66206703 69.487414   97.55754593]
3.289467866291169 [77.49221487 67.68158437 99.53799233]
3.2887779313044643 [ 77.44882515  66.88076982 100.3852539 ]
3.288647087337712 [ 77.44624372  66.52374184 100.74672222]
3.2886220914201396 [ 77.45383848  66.36357124 100.9003909 ]
3.288617263723048 [ 77.46181222  66.29119489 100.96542169]
3.288616316367331 [ 77.46778492  66.25822018 100.99277912]
3.288616126272483 [ 77.47172684  66.2430578  101.00419837]


In [175]:
# General gradient decent for extremum search

In [205]:
def f(x):
    return (x**3) + 6 * (x**2) + 12 * x + 5
def df(x):
    return 3 * (x**2) + 12 * x + 12

In [208]:
w = -1
for i in range(50):
    print(w, f(w), df(w))
    w -= 0.1 * df(w)

-1 -2 3
-1.3 -2.657000000000001 1.4699999999999989
-1.4469999999999998 -2.8308876230000006 0.917427
-1.5387426999999998 -2.9018636824639117 0.638274890409873
-1.6025701890409871 -2.937225780671966 0.47385136391675076
-1.6499553254326622 -2.9571085800008063 0.3675938225788613
-1.6867147076905484 -2.969251777143178 0.29444302313225457
-1.7161590100037738 -2.9771321497944907 0.241697122806114
-1.7403287222843853 -2.9824905806292925 0.20228751741137785
-1.760557474025523 -2.9862721079252115 0.17199816973511517
-1.7777572909990345 -2.989023027741993 0.14817546511226176
-1.7925748375102606 -2.991075491306667 0.12907559410168368
-1.805482396920429 -2.992640018407485 0.11351129372346236
-1.8168335262927753 -2.993854772666733 0.10064987127101865
-1.8268985134198772 -2.9948131654779324 0.08989237396874472
-1.8358877508167517 -2.9955799926373476 0.08079849099595293
-1.843967599916347 -2.9962012180433657 0.07303832962759671
-1.8512714328791067 -2.9967100963309594 0.06636056003350177
-1.85790748888