In [1]:
# Let's start with some simple linear regression with gradient decent

In [2]:
# Regression with mse

In [22]:
import numpy as np
np.random.seed(42)

In [10]:
x = np.random.randint(10, size=5)
y = np.random.randint(10, size=5)
print(x, y)
print(x - y)
print((x - y) ** 2)
print(np.sum((x - y) ** 2) ** 0.5)

[2 5 0 1 1] [0 7 6 3 3]
[ 2 -2 -6 -2 -2]
[ 4  4 36  4  4]
7.211102550927978


In [78]:
def mse(t, p):
    return (np.sum((p - t) ** 2) ** 0.5) / t.shape[0]

In [ ]:
np.random.seed()

In [44]:
mask = np.random.uniform(size=5)
d = np.random.rand(5, 2)
print(mask, d)
d[mask > 0.5]

[0.52640266 0.73158952 0.08162998 0.06035208 0.24710323] [[0.15954468 0.87178357]
 [0.21921399 0.97586526]
 [0.33689579 0.18211792]
 [0.78969851 0.65870778]
 [0.49819572 0.55536355]]


array([[0.15954468, 0.87178357],
       [0.21921399, 0.97586526]])

In [51]:
def split(data, target, rate):
    mask = np.random.uniform(size=data.shape[0])
    return data[mask >= rate], target[mask >= rate], data[mask < rate], target[mask < rate]

In [99]:
tmp = np.random.rand(10, 3)
print(tmp)
print(tmp[:,1])

[[0.26951186 0.19092659 0.69464096]
 [0.21871561 0.59530327 0.26463503]
 [0.66196894 0.81493973 0.77802524]
 [0.76085133 0.18772241 0.08838495]
 [0.69894883 0.36834721 0.43234623]
 [0.03114909 0.25957645 0.0336764 ]
 [0.87918577 0.24339668 0.55733717]
 [0.03897932 0.66684739 0.32302735]
 [0.89791919 0.88811819 0.32529062]
 [0.9009609  0.99615767 0.82541566]]
[0.19092659 0.59530327 0.81493973 0.18772241 0.36834721 0.25957645
 0.24339668 0.66684739 0.88811819 0.99615767]


In [230]:
data = np.random.rand(100, 3)
target = 10 * data[:,0] + 20 * data[:,1] + 30 * data[:,2] + np.random.normal(size=100)

In [231]:
print(data.shape)
print(target.shape)

(100, 3)
(100,)


In [16]:
import sklearn

In [17]:
from sklearn import linear_model

In [18]:
validate_model = linear_model.LinearRegression()

In [234]:
train_data, train_target, test_data, test_target = split(data, target, 0.8)
data = np.random.rand(100, 3)
target = 10 * data[:,0] + 20 * data[:,1] + 30 * data[:,2] + np.random.normal(size=100)

1.3723933228976921

In [243]:
validate_model.coef_

array([10.68397181, 19.9471113 , 30.1852103 ])

In [69]:
X = np.random.rand(10, 3)
y = np.random.rand(10)
w = np.random.rand(X.shape[1])
pred = np.matmul(X, w)
print(mse(pred, y))
a = 2 * np.matmul(pred - y, X)
a.shape

0.156993514335475


(3,)

In [271]:
class LinearModel:
    def fit(self, X, y, lr=0.01, iterations=1000, min_loss=1e-9):
        self.weights = np.random.rand(X.shape[1])
        self.train_losses = []
        for i in range(iterations):
            y_pred = np.dot(X, self.weights)
            loss = np.sum((y - y_pred) ** 2) / len(y)
            self.train_losses.append(loss)
            grad = np.dot(y_pred - y, X)
            if np.sum(np.abs(grad)) < min_loss:
                break
            self.weights -= lr * grad
            
    def predict(self, X):
        return np.dot(X, self.weights)

In [290]:
class LinearModelWithAdditionalElement:
    def fit(self, X, y, lr=0.01, iterations=1000, min_loss=1e-12):
        self.train_losses = []
        _X = np.concatenate((X, np.ones((len(X), 1))), axis=1)
        self.weights = np.random.rand(_X.shape[1])
        for i in range(iterations):
            y_pred = np.dot(_X, self.weights)
            loss = np.sum((y - y_pred) ** 2) / len(y)
            self.train_losses.append(loss)
            grad = np.dot(y_pred - y, _X)
            if np.sum(np.abs(grad)) < min_loss:
                break
            self.weights -= lr * grad
            
    def predict(self, X):
        _X = np.concatenate((X, np.ones((len(X), 1))), axis=1)
        return np.dot(_X, self.weights)

In [291]:
m = LinearModelWithAdditionalElement()
m.fit(test_data, test_target, lr=0.0001, iterations=100000)
sklearn.metrics.mean_squared_error(train_target, m.predict(train_data))  

1.3723933228975589

In [280]:
m = LinearModel()
m.fit(test_data, test_target, lr=0.0001, iterations=100000)
sklearn.metrics.mean_squared_error(train_target, m.predict(train_data))  

1.3857461690198216

In [292]:
validate_model.fit(test_data, test_target)
sklearn.metrics.mean_squared_error(train_target, validate_model.predict(train_data))

1.3723933228976921

In [148]:
train_target.shape

(22,)

In [235]:
10 * train_data[0][0] + 20 * train_data[0][1] + 30 * train_data[0][2]

28.179690617617403

In [236]:
train_target[0]

27.840999277695527

In [263]:
weights = np.zeros(3)
weights[0] = 9
weights[1] = 19
weights[2] = 29
# weights = np.random.rand(3)
grad_abs = 1
while grad_abs > 1e-8:
    y_pred = np.dot(train_data, weights)
    grad = np.dot(y_pred - train_target, train_data)
    loss = np.sum(np.abs(y_pred - train_target)) / len(train_data)
    weights = weights - 0.0001 * grad 
    grad_abs = np.sum(np.abs(grad))
print(weights, loss, np.sum(np.abs(grad)))

[10.93131018 21.43602032 28.02899201] 0.8326945250405758 9.999509267598933e-09


In [175]:
# General gradient decent for extremum search

In [205]:
def f(x):
    return (x**3) + 6 * (x**2) + 12 * x + 5
def df(x):
    return 3 * (x**2) + 12 * x + 12

In [264]:
w = -1
for i in range(50):
    w -= 0.1 * df(w)
print(w, f(w), df(w))

-1.9408439760549772 -2.9997929873293483 0.010498305506953187


In [1]:
import os

In [2]:
os.system('echo $PYTHONPATH')

0

In [3]:
os.getenv('PATH')

'/Users/krabchuk/anaconda3/bin:/Users/krabchuk/anaconda3/condabin:/usr/local/bin:/usr/bin:/Users/krabchuk/.nvm/versions/node/v19.6.0/bin:/Users/krabchuk/scripts:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki'

In [1]:
import ml_basics

ModuleNotFoundError: No module named 'ml_basics'

In [4]:
import sys
sys.path.append('/Users/krabchuk/tmp')

In [1]:
import sys
sys.path

['/Users/krabchuk/tmp/ml_basics/linear_models',
 '/Users/krabchuk/tmp/ml_basics',
 '/Users/krabchuk/anaconda3/lib/python310.zip',
 '/Users/krabchuk/anaconda3/lib/python3.10',
 '/Users/krabchuk/anaconda3/lib/python3.10/lib-dynload',
 '',
 '/Users/krabchuk/anaconda3/lib/python3.10/site-packages',
 '/Users/krabchuk/anaconda3/lib/python3.10/site-packages/PyQt5_sip-12.11.0-py3.10-macosx-11.1-arm64.egg',
 '/Users/krabchuk/anaconda3/lib/python3.10/site-packages/aeosa',
 '/Users/krabchuk/anaconda3/lib/python3.10/site-packages/mpmath-1.2.1-py3.10.egg',
 '/Users/krabchuk/anaconda3/lib/python3.10/site-packages/pycurl-7.45.1-py3.10-macosx-11.1-arm64.egg']

In [2]:
sys.path

['/Applications/PyCharm.app/Contents/plugins/python/helpers-pro/jupyter_debug',
 '/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev',
 '/Users/krabchuk/tmp/ml_basics/linear_models',
 '/Users/krabchuk/tmp/ml_basics',
 '/Users/krabchuk/anaconda3/lib/python310.zip',
 '/Users/krabchuk/anaconda3/lib/python3.10',
 '/Users/krabchuk/anaconda3/lib/python3.10/lib-dynload',
 '',
 '/Users/krabchuk/anaconda3/lib/python3.10/site-packages',
 '/Users/krabchuk/anaconda3/lib/python3.10/site-packages/PyQt5_sip-12.11.0-py3.10-macosx-11.1-arm64.egg',
 '/Users/krabchuk/anaconda3/lib/python3.10/site-packages/aeosa',
 '/Users/krabchuk/anaconda3/lib/python3.10/site-packages/mpmath-1.2.1-py3.10.egg',
 '/Users/krabchuk/anaconda3/lib/python3.10/site-packages/pycurl-7.45.1-py3.10-macosx-11.1-arm64.egg']