In [1]:
# Let's start with some simple linear regression with gradient decent

In [2]:
# Regression with mse

In [22]:
import numpy as np
np.random.seed(42)

In [10]:
x = np.random.randint(10, size=5)
y = np.random.randint(10, size=5)
print(x, y)
print(x - y)
print((x - y) ** 2)
print(np.sum((x - y) ** 2) ** 0.5)

[2 5 0 1 1] [0 7 6 3 3]
[ 2 -2 -6 -2 -2]
[ 4  4 36  4  4]
7.211102550927978


In [78]:
def mse(t, p):
    return (np.sum((p - t) ** 2) ** 0.5) / t.shape[0]

In [ ]:
np.random.seed()

In [44]:
mask = np.random.uniform(size=5)
d = np.random.rand(5, 2)
print(mask, d)
d[mask > 0.5]

[0.52640266 0.73158952 0.08162998 0.06035208 0.24710323] [[0.15954468 0.87178357]
 [0.21921399 0.97586526]
 [0.33689579 0.18211792]
 [0.78969851 0.65870778]
 [0.49819572 0.55536355]]


array([[0.15954468, 0.87178357],
       [0.21921399, 0.97586526]])

In [51]:
def split(data, target, rate):
    mask = np.random.uniform(size=data.shape[0])
    return data[mask >= rate], target[mask >= rate], data[mask < rate], target[mask < rate]

In [99]:
tmp = np.random.rand(10, 3)
print(tmp)
print(tmp[:,1])

[[0.26951186 0.19092659 0.69464096]
 [0.21871561 0.59530327 0.26463503]
 [0.66196894 0.81493973 0.77802524]
 [0.76085133 0.18772241 0.08838495]
 [0.69894883 0.36834721 0.43234623]
 [0.03114909 0.25957645 0.0336764 ]
 [0.87918577 0.24339668 0.55733717]
 [0.03897932 0.66684739 0.32302735]
 [0.89791919 0.88811819 0.32529062]
 [0.9009609  0.99615767 0.82541566]]
[0.19092659 0.59530327 0.81493973 0.18772241 0.36834721 0.25957645
 0.24339668 0.66684739 0.88811819 0.99615767]


In [100]:
data = np.random.rand(100, 3)
target = 10 * data[:,0] + 20 * data[:,1] + 30 * data[:,2] + np.random.normal(100)

In [101]:
print(data.shape)
print(target.shape)

(100, 3)
(100,)


In [16]:
import sklearn

In [17]:
from sklearn import linear_model

In [18]:
validate_model = linear_model.LinearRegression()

In [102]:
train_data, train_target, test_data, test_target = split(data, target, 0.8)

In [157]:
validate_model.fit(test_data, test_target)
sklearn.metrics.mean_squared_error(train_target, validate_model.predict(train_data))  

2.5610727861138885e-27

In [158]:
validate_model.coef_

array([10., 20., 30.])

In [69]:
X = np.random.rand(10, 3)
y = np.random.rand(10)
w = np.random.rand(X.shape[1])
pred = np.matmul(X, w)
print(mse(pred, y))
a = 2 * np.matmul(pred - y, X)
a.shape

0.156993514335475


(3,)

In [142]:
class LinearModel:
    def fit(self, X, y):
        self.weights = np.random.rand(X.shape[1])
        for i in range(100):
            y_pred = np.dot(X, self.weights)
            print
            loss = mse(y, y_pred)
            if i % 10 == 0:
                print(loss, self.weights)
            
            self.weights -= 0.01 * np.dot(y_pred - y, X)

In [148]:
train_target.shape

(22,)

In [174]:
weights = np.random.rand(train_data.shape[1])
for i in range(300000):
    y_pred = np.dot(train_data, weights)
    loss = mse(train_target, y_pred)
    if i % 10000 == 0:
        print(loss)
        #print(y_pred, train_target)
    grad = np.dot(y_pred - train_target, train_data) / train_data.shape[1] + 2 * weights
    weights = weights - 0.00001 * grad 
    

27.393146441177077
17.71119213097555
13.590605994853485
11.855919772306008
11.108370660011987
10.77491458056744
10.62172749911794
10.549639119462613
10.514884775298809
10.49762136993719
10.488697938861094
10.483841292149387
10.481030570597708
10.479294127374926
10.478153514684351
10.477364940009883
10.476798268285243
10.476379896833777
10.476065427106205
10.475826324922949
10.475643211660815
10.475502346339361
10.475393678821575
10.475309702913243
10.475244735765108
10.475194437822744
10.475155477458555
10.475125288296327
10.475101889294377
10.475083749210349


In [153]:
m = LinearModel()
m.fit(test_data, test_target)

14.789077800802525 [0.04191522 0.41918288 0.16820366]
3.312481524615864 [78.18058309 73.57440531 92.93486733]
3.293121837745023 [77.66206703 69.487414   97.55754593]
3.289467866291169 [77.49221487 67.68158437 99.53799233]
3.2887779313044643 [ 77.44882515  66.88076982 100.3852539 ]
3.288647087337712 [ 77.44624372  66.52374184 100.74672222]
3.2886220914201396 [ 77.45383848  66.36357124 100.9003909 ]
3.288617263723048 [ 77.46181222  66.29119489 100.96542169]
3.288616316367331 [ 77.46778492  66.25822018 100.99277912]
3.288616126272483 [ 77.47172684  66.2430578  101.00419837]
